DROP TABLE IF EXISTS occ;
CREATE TABLE occ(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    code VARCHAR(10) NOT NULL
);
LOAD DATA INFILE "occ_tracking_data.csv" INTO TABLE occ FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES (id, code);